package com.user.controller;

import com.user.service.UserService;
import com.user.model.User;
import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import java.sql.Timestamp;

public class RegistrationServlet extends HttpServlet {
    private UserService userService = new UserService();

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Get the form data from the request
        String email = request.getParameter("email");
        String password = request.getParameter("password");
        String name = request.getParameter("name");
        String phone = request.getParameter("phone");
        String address = request.getParameter("address");

        // Generate userId (since it's auto-generated by the DB, you can set it to 0)
        int userId = 0;

        // Get the current timestamp for the createdAt field
        Timestamp createdAt = new Timestamp(System.currentTimeMillis());

        // Create a new User object with all required fields
        User user = new User(userId, email, password, name, phone, address, createdAt);

        // Call the userService to handle user registration logic
        boolean success = userService.registerUser(user);

        if (success) {
            response.sendRedirect("login.html"); // Redirect to login after successful registration
        } else {
            response.sendRedirect("registration.html"); // Redirect back to registration on failure
        }
    }
}
